version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: false  # Do not overwrite existing files
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh  # Add cleanup script to remove existing files
      timeout: 300
      runas: root
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
